name: Docker CI

# Este robot se activa cuando hacemos push a la rama master
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t ai-calculator .

    - name: Run Pytest inside Docker
      run: docker run ai-calculator python3 -m pytest